WINDOW_WIDTH = 2560
WINDOW_HEIGHT = 1440
VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144
CAMERA_SPEED = 100
TILE_SETS_WIDE = 6
TILE_SETS_TALL = 10
TILE_SET_WIDTH = 5
TILE_SET_HEIGHT = 4

TILE_SETS = TILE_SETS_WIDE * TILE_SETS_TALL
TILE_ID_EMPTY = 5
TILE_ID_GROUND = 3
COLLIDABLE_TILES = {
    TILE_ID_GROUND
}